repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=5000"]
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check src and tests
        entry: ruff check --fix src tests
        language: system
        pass_filenames: false
        files: ^(src|tests)/.*\.py$

      - id: ruff-format
        name: ruff format src and tests
        entry: ruff format src tests
        language: system
        pass_filenames: false
        files: ^(src|tests)/.*\.py$

      - id: bandit-src
        name: bandit security scan src
        entry: bandit -r src -ll -ii
        language: system
        pass_filenames: false
        files: ^src/.*\.py$
